In [ ]:
import numpy as np

In [2]:
arr = np.random.randint(1,51,(5,4))
print(arr)

[[32 43 10 46]
 [44 28 31 42]
 [37 10 50 35]
 [18  1 24 37]
 [22 38 35 44]]


In [ ]:
# Extraxting the elements along the anti-diagonal
i = 0
j = 3
while i<=4 and j>=0:
    print(arr[i,j])
    i = i + 1
    j = j - 1

46
31
10
18


In [9]:
# Maximum value in each row
row_max = np.max(arr,axis=1)
print(row_max.reshape(-1,1))

[[46]
 [44]
 [50]
 [37]
 [44]]


In [11]:
# Elements greater than or equal to overall mean
overall_mean = np.mean(arr)
print("The overall mean is: ",overall_mean)
new_arr = arr[arr >= overall_mean]
print(new_arr)

The overall mean is:  31.35
[32 43 46 44 42 37 50 35 37 38 35 44]


In [20]:
def numpy_boundary_traversal(matrix):
    left = 0
    right = len(matrix[0]) - 1
    top = 0
    bottom = len(matrix) - 1
    boundary = list()

    for i in range(left,right+1):
        boundary.append(matrix[top][i])
    top = top + 1

    for i in range(top,bottom+1):
        boundary.append(matrix[i][right])
    right = right - 1
    if top <= bottom:
        for i in range(right,left-1,-1):
            boundary.append(matrix[bottom][i])
        bottom = bottom - 1
    if left <= right:
        for i in range(bottom,top-1,-1):
            boundary.append(matrix[i][left])
        left = left + 1
    return boundary

In [21]:
boundary = numpy_boundary_traversal(arr)
print(boundary)

[32, 43, 10, 46, 42, 35, 37, 44, 35, 38, 22, 18, 37, 44]
