In [39]:
import numpy as np

##### Arrays in NumPy

In [40]:
arr = np.array([1,2,3]) # 1D array
arr = np.array([[1,2,3],[4,5,6]]) # 2D array

##### Slicing in Arrays

In [41]:
a = np.array([10,20,30,40,50])
print(a[1:4]) # [20,30,40]
print(a[:3]) # [10,20,30]
print(a[::2]) # [10,30,50]
print(a[-2:]) # [40,50]

b = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

print(b[0, :]) #first row
print(b[:, 1]) #second row
print(b[1:3, 0:2]) #submatrix

[20 30 40]
[10 20 30]
[10 30 50]
[40 50]
[1 2 3]
[2 5 8]
[[4 5]
 [7 8]]


#### Reshape

In [42]:
a = np.array([1, 2, 3, 4, 5, 6])
b = a.reshape(2, 3)

print(b)

[[1 2 3]
 [4 5 6]]


#### Arange

In [43]:
arr = np.arange(0,10,2)
print(arr)

[0 2 4 6 8]


##### Other Functions

In [44]:
# eye
e = np.eye(3,3)
print(e)
print('\n============')
# ndim
print("Dimension of the array e: ",np.ndim(e))
print('\n============')
# size 
print("Size of the array e: ",e.size)
print('\n============')
# dtype
print("Data type of the elements of e: ",e.dtype)
print('\n============')
# itemsize
print("Size of one array element in bytes: ", e.itemsize)
print('\n============')
# flatten
b = e.flatten()
print("Flattened e into b : ",b)
print('\n============')

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Dimension of the array e:  2

Size of the array e:  9

Data type of the elements of e:  float64

Size of one array element in bytes:  8

Flattened e into b :  [1. 0. 0. 0. 1. 0. 0. 0. 1.]



#### NumPy Vectorised Functions

In [45]:
# element wise arithematic
print("Element wise Arithematic")
a = np.array([1,2,3])
b = np.array([10,20,30])
print("a + b = ",a+b)
print("a - b = ",a-b)
print("a * b = ",a*b)
print("a / b = ",a/b)
print('\n===========')
print('Universal Functions')
angles = np.array([0, np.pi/2 , np.pi])
sines = np.sin(angles)
print("Sin of the angles : ",sines)
print('\n============')
print('Statistical Functions in NumPy')
a = np.array([10,20,35,40,50])
print("Mean of the data",np.mean(a))
print("Median of the data",np.median(a))
b = np.random.randint(1,101,(3,3))
print("Random Array b :")
print(b)
print("Mean of each row of b : ")
print(np.mean(b,axis=1).reshape(-1,1))
print('\n============')
print("Boolean Operations")
a = np.array([1, 2, 3, 4])
b = np.array([2, 2, 3, 5])
print((a == b) | (a < b))

Element wise Arithematic
a + b =  [11 22 33]
a - b =  [ -9 -18 -27]
a * b =  [10 40 90]
a / b =  [0.1 0.1 0.1]

Universal Functions
Sin of the angles :  [0.0000000e+00 1.0000000e+00 1.2246468e-16]

Statistical Functions in NumPy
Mean of the data 31.0
Median of the data 35.0
Random Array b :
[[88 29 93]
 [ 8 56 88]
 [35 82 67]]
Mean of each row of b : 
[[70.        ]
 [50.66666667]
 [61.33333333]]

Boolean Operations
[ True  True  True  True]


##### Broadcasting

In [46]:
print('Add Scalar to an array')
a = np.array([1,2,3,4])
b = 5
print("a + b : ",a+b)
print('\n============')
print('Add 1D to 2D Array')
A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([10, 20, 30])
print('A + B : ')
print(A + B)
print('\n============')
print('Column wise Broadcasting')
A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([[10],
              [20]])
print('A + B : ')
print(A + B)
print('\n============')
print('ERROR IN BROADCASTING')
a = np.array([1, 2, 3])
b = np.array([[1,2],[3,4]])
print(a+b)

Add Scalar to an array
a + b :  [6 7 8 9]

Add 1D to 2D Array
A + B : 
[[11 22 33]
 [14 25 36]]

Column wise Broadcasting
A + B : 
[[11 12 13]
 [24 25 26]]

ERROR IN BROADCASTING


ValueError: operands could not be broadcast together with shapes (3,) (2,2) 